version: "3"
services:
    wordpress:
        build: ./my-wordpress
        ports:
            - "${PORT}:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: .env
        volumes:
            - ./wp-content/themes/${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
            - ./wp-content/uploads/:/var/www/html/wp-content/uploads
    db:
        image: mysql:${MYSQL_VERSION}
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
